name: Java CI with Maven
permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write
  id-token: write
on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode package --file pom.xml -DskipTests
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_failure: true
